2020-10-10 16:16:34,015 ERROR: Exception on /translate [POST] [in c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Joseph Staresinovic\website\app\routes.py", line 204, in translate_text
    return jsonify({'text': translate(request.form['text'],
NameError: name 'translate' is not defined
2020-10-10 16:17:07,649 ERROR: Exception on /translate [POST] [in c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Joseph Staresinovic\website\app\routes.py", line 204, in translate_text
    return jsonify({'text': translate(request.form['text'],
NameError: name 'translate' is not defined
2020-10-10 16:17:47,260 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 16:19:23,624 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 16:21:24,210 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 16:22:17,749 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 16:35:06,253 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 16:41:15,859 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 16:53:52,214 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 16:54:30,914 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 16:54:52,152 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 16:56:10,110 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 16:56:19,250 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 16:57:10,403 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 16:57:18,237 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 16:57:23,333 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 17:03:52,091 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 17:14:08,281 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 17:17:32,337 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 17:18:24,025 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 17:41:02,763 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 17:41:46,016 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 21:19:03,632 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 21:19:25,313 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-11 17:15:27,533 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:57]
2020-10-11 17:15:56,396 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:57]
2020-10-11 17:15:58,931 ERROR: Exception on /login [GET] [in c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Joseph Staresinovic\website\app\routes.py", line 66, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
